### PR TITLE
Migrate to Github Actions

### PR DESCRIPTION
**Pull request by maximlt**
Supersede #66

### CODE REVIEW

**Comment by maximlt** [comment]
@jbednar the CI has not been migrated to Github actions and is all green. I had to remove Windows-py2.7 from the test matrix, it raised an error while installing ipykernel in the`doit develop_install` step for which I found no easy fix online. Note that the test suite on py2.7 is only running `test_unit`, it ignores `test_examples` and `test_unit_extra`. The docs and releases are built based on tags, similarly to the other holoviz projects.

The failing AppVeyor tests that are shown in this PR can be ignored I think, I've deleted the appveyor configuration file.

You might want to check that the expected secrets (CONDA_UPLOAD_TOKEN, PPU, PPP, ACCESS_TOKEN, GITHUB_TOKEN) are well configured in the repo's settings, to which I don't have access. You might want first to tag a dev release to check that the docs and release workflows work well, before trying to do a proper release.

**Comment by philippjfr** [comment]
>You might want to check that the expected secrets (CONDA_UPLOAD_TOKEN, PPU, PPP, ACCESS_TOKEN, GITHUB_TOKEN) are well configured in the repo's settings, to which I don't have access. You might want first to tag a dev release to check that the docs and release workflows work well, before trying to do a proper release.

They are configured for the whole holoviz org, so they should be available.

**Comment by maximlt** [comment]
Ok sweet good to know!

**Comment by jbednar** [comment]
Fabulous; thanks @maximlt ! I'll merge and we'll see how it goes!

**Pull request merged**
