### PR TITLE
Update links and text to point to holoviz.org

### PR DESCRIPTION
**Pull request by jlstevens**
The string 'pyviz' appears in a few places in the code but I don't intend to update those just yet (e.g for the conda channel). Some of the text in the README about HoloViz/PyViz should also appear on the website but that is for a separate PR.

### CODE REVIEW

**Comment by jlstevens** [comment]
@jbednar The dev build of the website is [now up](https://pyviz-dev.github.io/colorcet/about.html). If the changes look good to you, it is ready to merge.

**Comment by jbednar** [comment]
Looks good, thanks!

**Comment by ArchangeGabriel** [comment]
You still need to change it in the repo description (at the top here: https://github.com/holoviz/colorcet).

**Comment by jbednar** [comment]
Good catch! I've updated that now.

**Pull request merged**
