### PR TITLE
Update installation code fence

### PR DESCRIPTION
**Pull request by kianmeng**
List of changes:
- add missing language for code fence
- use `python -m pip` installation method

### CODE REVIEW

**Comment by jbednar** [comment]
Specifying the language looks useful, thanks! What's the reasoning behind using `python -m pip` instead of just `pip`? It doesn't seem to me like most users would need the more complicated version.

**Comment by kianmeng** [comment]
@jbednar See https://snarky.ca/why-you-should-use-python-m-pip/

**Comment by jbednar** [comment]
Thanks!

**Comment by kianmeng** [comment]
:partying_face: :partying_face: :partying_face: :partying_face: :partying_face:

**Pull request merged**
