### PR TITLE
Simplify aliases and import new cmaps from Dec 2020

### LINKED ISSUE #56: Update colorcet to upstream, especially new Gouldian Parula replacement
### New
- C3 - Cyclic: white - red - black - blue
- C6 - "Six colour cyclic with primaries and secondaries matched in lightness"
- C7 - Cyclic Yellow - Magenta - Cyan - Green - Yellow
- L20 - Parula replacement "Gouldian"
- R4 - Rainbow colour map from blue to red

### Changed
- D1-D9, L1-L9 renamed to D01-D09, L01-L09
- Floats have higher precision

There actually look to be even more in colorcet.m, I guess that's the ultimate canonical source?

I'm a bit unsure how to integrate these changes into CET_to_py.py, especially the D01-D09 and L01-09 stuff. Or maybe this project keeps the original CSV names?

### LINKED ISSUE #60: Allow more aliases
[`colorcet.m`](https://www.peterkovesi.com/matlabfns/Colourmaps/colorcet.m) (essentially the "canonical" upstream, though created by [`cmap.m`](https://www.peterkovesi.com/matlabfns/Colourmaps/cmap.m)) offers more aliases for colorcet maps than are possible via `CET_to_py.py`, since the `aliases` dict is a one-to-one mapping of descriptor name to alias (e.g. `linear_kryw_0-100_c71_n256: 'fire'`)

#### Describe the solution you'd like
Change `aliases` in CET_to_py.py to a dict of lists where each descriptorname can have multiple aliases. Rework uses of `aliases` to handle a list of values returned for each key.

### PR DESCRIPTION
**Pull request by randallpittman**
## Summary
In Dec. 2020 Peter updated the CET colormaps. This PR contains multiple changes:
1. Change `aliases` to a dict of lists. This simplifies the logic of finding all the aliases for a given name and makes it easy to add aliases for a given map.
2. Add new colormaps available in the Dec 2020 update to `colorcet.m` from Peter Kovesi, as well as at most one alias for any colormaps that do not yet have one.

## Notes
- This PR depends on, and follows after, PR #64, which makes each colormap's algorithmic name AKA descriptorname the name of the CSV file.
- Resolves #60 
- Resolves #56 
- Since the `CET_` name may in some cases be the only alias to a map, I have not removed those, though we talked about it previously. (Actually, I did at first, but then reverted the change). If someone wants to do this it's pretty easy--just remove `cetnames`, `cetnames_flipped`, and anything that references those variables from `CET_to_py.py`, rerun `CET_to_py.py` and update the tests.
- In this PR new colormap CSVs are not downloaded from Peter's site (as he doesn't have them all there anyway) but rather are generated from `colorcet.m` (using MATLAB/Octave script `make_csvs_from_colorcet.m`), since `colorcet.m` is the "upstream" of those CSVs. Some of the existing CSV colormaps in holoviz/colorcet don't exactly match what what's in `colorcet.m` but what's already here is being left as-is.
- A few CSVs have been renamed or removed as duplicates of existing CSVs with the same colormap. All CET CSVs should now have the algorithmic name (e.g. `linear_kbc_5_95_c73` instead of `linear_blue_5_95_c73`. The old names (...`_blue_`...) may still be used.
- All existing aliases have been retained. New aliases have been added only for new colormaps or where aliases did not previously exist.
- Instructions for merging future additions from `colorcet.m` are at the top of `make_csvs_from_colorcet.m` and `CET_merge.py`.

### CODE REVIEW

**Comment by randallpittman** [comment]
Since `aliases` and `mapping` were reordered alphabetically, and `mapping` was renamed to `cetnames`, the attached file shows the actual changes to these dicts.

[aliases_cetnames_diff.txt](https://github.com/holoviz/colorcet/files/6064723/aliases_cetnames_diff.txt)

**Comment by randallpittman** [comment]
Just FYI I'm still planning to finish this ASAP. Work has kept me busy.

**Comment by jbednar** [comment]
Cool, thanks. I'm excited to see these made available, but no rush!

**Comment by jbednar** [comment]
I'd guess you're still busy, but just checking in to see if you know when this can get wrapped up? I'd love to make a new release so people can use this cool stuff!

**Comment by randallpittman** [comment]
This is ready to go, from my end.

**Review by jbednar — APPROVED** [review]
Thanks for all this work! I can't spot any problems with it, so now that CI isn't broken any more I'll merge it now and do more testing locally before making a release.  Sorry for the long delay while we focused on Param!

**Comment by randallpittman** [comment]
@jbednar You're welcome! It was a fun pet project to take up. Also, Param looks amazing--I had not looked into it before.

**Pull request merged**
